version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.2-fpm
    container_name: vp-php
    volumes:
      - './:/var/www/html'
    networks:
      - vp-network

  composer:
    image: composer:latest
    container_name: vp-composer
    volumes:
      - './:/var/www/html'
    depends_on:
      - php
    networks:
      - vp-network

  apache:
    image: httpd:latest
    container_name: vp-apache
    ports:
      - "80:80"
    volumes:
      - './:/var/www/html'
      - './docker:/usr/local/apache2/htdocs'
    depends_on:
      - php
    networks:
      - vp-network

  mysql:
    image: mysql:8
    container_name: vp-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - vp-network

networks:
  vp-network:
    driver: bridge
