version: '3'

services:
  apache:
    build:
      context: .
      dockerfile: ./config/apache/Dockerfile
    image: httpd:latest
    container_name: web-apache
    ports:
      - "80:80"
    volumes:
      - './app:/var/www/html'
      - './config/apache/apache.conf:/usr/local/apache2/conf/extra/apache.conf'
    depends_on:
      - php
    networks:
      - web-network

  php:
    build:
      context: .
      dockerfile: ./config/php/Dockerfile
    image: php:8.2-fpm
    container_name: web-php
    volumes:
      - './app:/var/www/html'
      - './config/php/php.ini:/usr/local/etc/php/php.ini'
    networks:
      - web-network

  composer:
    image: composer:latest
    container_name: web-composer
    volumes:
      - './app:/var/www/html'
    depends_on:
      - php
    networks:
      - web-network

  mysql:
    image: mysql:8
    container_name: web-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - web-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    platform: linux/amd64
    ports:
      - "8081:8081"

networks:
  web-network:
    driver: bridge
